[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/weather/analysis"
  to = "/.netlify/functions/weather"
  status = 200

[[redirects]]
  from = "/api/weather/date/:date"
  to = "/.netlify/functions/date"
  status = 200

[[redirects]]
  from = "/api/weather/cities"
  to = "/.netlify/functions/cities"
  status = 200
